resolver: lts-16.26
compiler: ghc-8.8.4

# Thanks for how to build: 
# https://brianbuccola.com/how-to-install-xmonad-and-xmobar-via-stack/
# https://quinoa42.github.io/en/oceanus/hie-and-xmonad/

packages:
- xmobar-git
- xmonad-git
- xmonad-contrib-git

flags:
 xmobar:
   all_extensions: true
   with_threaded: true
   with_alsa: true
   with_xft: true

extra-deps: []
flags: {}
extra-package-dbs: []



